### ISSUE TITLE
New issues

### ISSUE THREAD

**Issue by treviskjellberg22** [Edouard127/reddit-placebot-2023#25]
Waiting for login to finish...
Error receiving message from socket EOF
2023-07-22T16:31:17.920-0700    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "SacrifiedGoat"}
2023-07-22T16:31:35.233-0700    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "NewAvatar22"}
Error receiving message from socket EOF

Then it stops

**Comment by r4ngu** [comment]
How much accounts do you have on your users.json? Maybe you just have to wait some seconds, it normally happens to me even.

**Comment by treviskjellberg22** [comment]
I have two accounts, it shows that the login was successful then prints that error message. I waited longer and it just automatically stopped without printing anything else.

**Comment by treviskjellberg22** [comment]
Am I missing any setup with Tor? I installed the expert bundle and its on my C:/
I'll admit I have no clue what I'm doing. I'll provide as many details as possible

**Comment by Edouard127** [comment]
You have to put the Tor/tor inside your windows environment variables

**Comment by treviskjellberg22** [comment]
Added C:\Users\***\Desktop\Tor Browser (The Tor folder is on my desktop) to PATH, and now I'm encountering:

Waiting for login to finish...
2023-07-22T16:44:47.646-0700    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "SacrifiedGoat"}
2023-07-22T16:44:47.770-0700    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "SacrifiedGoat"}
panic: bmp: invalid format: not a BMP file

goroutine 98 [running]:
main.LoadBMP(0x0, 0x0)
        C:/Users/****/Desktop/reddit-placebot-2023-master/bmp.go:72 +0x27c
main.(*Client).connect(0xa61c320, 0xa6201e0)
        C:/Users/****/Desktop/reddit-placebot-2023-master/client.go:192 +0x78b
created by main.(*Client).Login
        C:/Users/****/Desktop/reddit-placebot-2023-master/client.go:80 +0x636
PS C:\Users\****\Desktop\reddit-placebot-2023-master>

I haven't changed any files, so I'm not sure why I'm getting an extension error. My images file is images.bmp

**Comment by Edouard127** [comment]
Are you sure It's a bmp

**Comment by treviskjellberg22** [comment]
![Capture](https://github.com/Edouard127/reddit-placebot-2023/assets/140280915/1829ff43-bc37-4464-9dc3-1f0c54c67908)
100% positive, I haven't even changed the sample bmp yet.

**Comment by Edouard127** [comment]
Maybe it's a different bmp format
Try with this image https://people.math.sc.edu/Burkardt/data/bmp/bmp_24.bmp

**Comment by treviskjellberg22** [comment]
```
2023-07-22T16:55:19.285-0700    INFO    reddit-placebot-2023-master/worker.go:45        Placing client after wait       {"username": "NewAvatar22"}
Placing pixel {145 102} {255 255 255} 4 {645 102}
2023-07-22T16:55:21.334-0700    ERROR   reddit-placebot-2023-master/client.go:291       Error sending request   {"username": "NewAvatar22", "error": "Post \"https://gql-realtime-2.reddit.com/query\": socks connect tcp 127.0.0.1:9050->gql-realtime-2.reddit.com:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it."}
```

I think that fixed it. Now just getting these errors repeating. If that's how it's supposed to look, where should I go to change the coordinates it pastes over?

**Comment by treviskjellberg22** [comment]
I got the same error for the first "placing client" lines as well. Error sending request

**Comment by treviskjellberg22** [comment]
Tried turning off my firewall to no avail

**Comment by treviskjellberg22** [comment]
Also made sure I have the path to get to Tor Experts exe under PATH

**Comment by treviskjellberg22** [comment]
```
Waiting for login to finish...
2023-07-22T17:28:00.749-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "NewAvatar22"}
2023-07-22T17:28:00.749-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "SacrifiedGoat"}
Login finished!
Waiting for board data
2023-07-22T17:28:00.956-0700    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "SacrifiedGoat"}
Board data received!
2023-07-22T17:28:01.286-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "SacrifiedGoat"}
Placing pixel {141 147} {212 215 217} 4 {641 147}
2023-07-22T17:28:03.794-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "NewAvatar22"}
Placing pixel {159 51} {156 105 38} 4 {659 51}
2023-07-22T17:28:05.753-0700    INFO    reddit-placebot-2023-master/client.go:307       There was an error placing pixel        {"username": "NewAvatar22", "message": "Pixel was not placed, or was placed somewhere else"}
```

Think I got it working good, it's just stopped here now

**Comment by Edouard127** [comment]
The not placed pixel error is very weird
I cannot reproduce it when I want to
It's reddit messing with new accounts

**Comment by Edouard127** [comment]
What exactly did you changed to fix it ?

**Comment by treviskjellberg22** [comment]
The accounts work when placing it manually, just not with the bot.
The last error was fixed by uninstalling Tor Expert, and reinstalling + opening it

**Comment by treviskjellberg22** [comment]
I'll try out a new batch of old accounts.

**Comment by treviskjellberg22** [comment]
```
2023-07-22T17:39:17.010-0700    INFO    reddit-placebot-2023-master/client.go:307       There was an error placing pixel        {"username": "RedditAvatars420", "message": "Pixel was not placed, or was placed somewhere else"}
```
Same errors with old accounts that haven't tried r/place yet. Works when manually placing them

**Comment by Edouard127** [comment]
> ```
> 2023-07-22T17:39:17.010-0700    INFO    reddit-placebot-2023-master/client.go:307       There was an error placing pixel        {"username": "RedditAvatars420", "message": "Pixel was not placed, or was placed somewhere else"}
> ```
> 
> Same errors with old accounts that haven't tried r/place yet. Works when manually placing them Added note: It automatically stops running after that error

It doesn't stop, It's just in the queue
And like I said before
I can't investigate this error

**Comment by treviskjellberg22** [comment]
When I say it stops, it goes back to being able to type in PowerShell, meaning nothing is running.
All good that you can't investigate it, just figured I'd give as many details as possible.

**Comment by treviskjellberg22** [comment]
Is there a settings config where I can change where it places? Might be the problem.

**Comment by Edouard127** [comment]
> Is there a settings config where I can change where it places? Might be the problem.

-minX -minY
This is the top left point

**Comment by treviskjellberg22** [comment]
```
PS C:\Users\*\Desktop\reddit-placebot-2023-master> .\redditplacebot.exe -minX=409 -minY=-349
Waiting for login to finish...
2023-07-22T17:51:29.091-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "EggMan1440"}
2023-07-22T17:51:29.091-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "RedditAvatars420"}
Login finished!
Waiting for board data
2023-07-22T17:51:29.205-0700    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "RedditAvatars420"}
Board data received!
2023-07-22T17:51:29.540-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "EggMan1440"}
Placing pixel {466 -194} {36 80 164} 1 {966 806}
2023-07-22T17:51:30.771-0700    INFO    reddit-placebot-2023-master/client.go:311       Error placing pixel     {"username": "EggMan1440", "message": "Ratelimited"}
2023-07-22T17:51:30.771-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "RedditAvatars420"}
Placing pixel {455 -153} {255 255 255} 1 {955 847}
2023-07-22T17:51:32.116-0700    INFO    reddit-placebot-2023-master/client.go:311       Error placing pixel     {"username": "RedditAvatars420", "message": "Ratelimited"}
```

New error, this one makes more sense. I'm ratelimited, so should I just wait 5 mins and rerun it?

**Comment by Edouard127** [comment]
> ```
> PS C:\Users\*\Desktop\reddit-placebot-2023-master> .\redditplacebot.exe -minX=409 -minY=-349
> Waiting for login to finish...
> 2023-07-22T17:51:29.091-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "EggMan1440"}
> 2023-07-22T17:51:29.091-0700    INFO    reddit-placebot-2023-master/client.go:48        Login successful        {"username": "RedditAvatars420"}
> Login finished!
> Waiting for board data
> 2023-07-22T17:51:29.205-0700    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "RedditAvatars420"}
> Board data received!
> 2023-07-22T17:51:29.540-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "EggMan1440"}
> Placing pixel {466 -194} {36 80 164} 1 {966 806}
> 2023-07-22T17:51:30.771-0700    INFO    reddit-placebot-2023-master/client.go:311       Error placing pixel     {"username": "EggMan1440", "message": "Ratelimited"}
> 2023-07-22T17:51:30.771-0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "RedditAvatars420"}
> Placing pixel {455 -153} {255 255 255} 1 {955 847}
> 2023-07-22T17:51:32.116-0700    INFO    reddit-placebot-2023-master/client.go:311       Error placing pixel     {"username": "RedditAvatars420", "message": "Ratelimited"}
> ```
> 
> New error, this one makes more sense. I'm ratelimited, so should I just wait 5 mins and rerun it?

It will re-run by itself

**Comment by treviskjellberg22** [comment]
Sweet, I think it's fixed then. Thank you for the help, I know it was probably frustrating lol

**Comment by treviskjellberg22** [comment]
```
Placing pixel {534 -336} {137 141 144} 2 {2034 -336}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*Client).Place(0xa4713b0, 0xa425f40)
        C:/Users/trevi/OneDrive/Desktop/reddit-placebot-2023-master/client.go:306 +0x14e7
main.(*Worker).Run(0xa425f80)
        C:/Users/trevi/OneDrive/Desktop/reddit-placebot-2023-master/worker.go:50 +0x5f1
main.main()
        C:/Users/trevi/OneDrive/Desktop/reddit-placebot-2023-master/main.go:51 +0x636
PS C:\Users\trevi\OneDrive\Desktop\reddit-placebot-2023-master>
```
Used new accounts to fix being ratelimited, getting this now. Sorry

**Comment by Edouard127** [comment]
> ```
> Placing pixel {534 -336} {137 141 144} 2 {2034 -336}
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> main.(*Client).Place(0xa4713b0, 0xa425f40)
>         C:/Users/***/Desktop/reddit-placebot-2023-master/client.go:306 +0x14e7
> main.(*Worker).Run(0xa425f80)
>         C:/Users/***/Desktop/reddit-placebot-2023-master/worker.go:50 +0x5f1
> main.main()
>         C:/Users/***/Desktop/reddit-placebot-2023-master/main.go:51 +0x636
> PS C:\Users\***\Desktop\reddit-placebot-2023-master>
> ```
> 
> Used new accounts to fix being ratelimited, getting this now. Sorry

I know what causes this issue

**Comment by treviskjellberg22** [comment]
What's the problem?

**Comment by Edouard127** [comment]
> What's the problem?

Basically r/place have a rather weird canvas system
The grid looks like that

0 | 1 | 4
2 | 3 | 5

So I have to apply offset on the point based on the canvas id, but it's wrong

**Comment by treviskjellberg22** [comment]
Seems a bit complicated, think I'll give up here lol.
Thank you for helping me throughout the entire process. Just seems like I'm encountering too many issues to fix it.
