### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by anelfer** [Edouard127/reddit-placebot-2023#52]
```
Get "https://api.seeip.org/jsonip": EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x1050d7b5c]

goroutine 571 [running]:
main.listenForCircuit(0x0?, 0x0?)
        /Users/anelfer/work/reddit-placebot-2023/util.go:109 +0x2dc
created by main.(*Client).Setup
        /Users/anelfer/work/reddit-placebot-2023/client.go:245 +0x384
```

**Comment by Edouard127** [comment]
#30
