### ISSUE TITLE
index out of range [0]

### ISSUE THREAD

**Issue by KoyuKansou** [Edouard127/reddit-placebot-2023#64]
E:\rplacebot\sexrplace727> ./redditplacebot -minX=851 -minY=-192
Waiting for login to finish...
2023-07-24T00:41:03.863+0700    INFO    reddit-placebot-2023-master/client.go:81        Login successful        {"username": "Direct_Log_9991"}
2023-07-24T00:41:04.333+0700    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "Direct_Log_9991"}
Login finished!
Waiting for board data
Board data received!
2023-07-24T00:41:06.129+0700    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "Direct_Log_9991"}
Placing pixel {866 -174} {0 163 104} 2 {2366 -174}
panic: runtime error: index out of range [0] with length 0

any help ?

**Comment by Edouard127** [comment]
Outdated error, please use the latest commit

**Comment by KoyuKansou** [comment]
> Outdated error, please use the latest commit

PS E:\rplacebot\sexrplace727> ./redditplacebot -minX=840 -minY=-192
Waiting for login to finish...
2023-07-24T13:29:42.393+0700    INFO    reddit-placebot-2023/client.go:84       Login successful        {"username": "Popular-Homework-259 "}
Login finished!
Waiting for board data
2023-07-24T13:29:43.925+0700    INFO    reddit-placebot-2023/board.go:50        Controller changed      {"username": "Popular-Homework-259 "}
Board data received!
2023-07-24T13:29:45.809+0700    INFO    reddit-placebot-2023/worker.go:49       Placing client  {"username": "Popular-Homework-259 "}
Placing pixel {868 -172} {255 153 170} 2 {2368 -172}
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*Client).Place(0xc000222510, 0x103e1ca?)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/client.go:307 +0x142f
main.(*Worker).Run(0xc00022c180)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/worker.go:50 +0x58f
main.main()
        D:/a/reddit-placebot-2023/reddit-placebot-2023/main.go:51 +0x67a

same error, even with latest commit
