### ISSUE TITLE
panic: Please add users to the users.json file?

### ISSUE THREAD

**Issue by oejzis** [Edouard127/reddit-placebot-2023#78]
![Screenshot 2023-07-24 125234](https://github.com/Edouard127/reddit-placebot-2023/assets/102473438/84277af2-df63-4930-b5b9-a39467ab7b16)
![Screenshot 2023-07-24 125658](https://github.com/Edouard127/reddit-placebot-2023/assets/102473438/6719cac2-7908-4b7d-a110-9cdd60b1b3b5)

**Comment by GilDev** [comment]
Try to `cd` first into the executable’s directory and then launch the script there. Be sure your users.json file is in the “data” directory alongside the executable.

**Comment by Obelisx** [comment]
> Try to `cd` first into the executable’s directory and then launch the script there. Be sure your users.json file is in the “data” directory alongside the executable.

I'm using PowerShell on the directory, but my accounts won't login.
It's showing ```
Waiting for login to finish...
2023-07-25T01:21:52.979+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
2023-07-25T01:21:57.461+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/lhoog/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
Login finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x50a3cf]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xa218090)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/board.go:43 +0x7f
main.(*Worker).Run(0xa206260)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/worker.go:37 +0x4e
main.main()
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:47 +0x5b8
```

Any idea what this could be? the json file is filled in correctly.
