### ISSUE TITLE
[Crash] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yetAnother-throwaway-122** [Edouard127/reddit-placebot-2023#94]
Bot crashing using a build with the latest commits. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x9da30f]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xab18000)
        C:/Users/xxxxxx/Desktop/place-test/reddit-placebot-2023/board.go:43 +0x7f
main.(*Worker).Run(0xab08160)
        C:/Users/xxxxxx/Desktop/place-test/reddit-placebot-2023/worker.go:37 +0x4e
main.main()
        C:/Users/xxxxxx/Desktop/place-test/reddit-placebot-2023/main.go:47 +0x5b8
        ```

**Comment by Edouard127** [comment]
Can not reproduce, need more info

**Comment by Obelisx** [comment]
Did you manage to fix this throwaway?
