### ISSUE TITLE
Login failed {"username": "", "username": ""}

### ISSUE THREAD

**Issue by Obelisx** [Edouard127/reddit-placebot-2023#97]
Despite using the exact layout as shown in the original users.json.rename file, the build fails to log into my accounts.
I use PowerShell on the directory and have Tor 100% bootstrapped.
After getting the following errors, my json file is empty showing just `[]` (after trying terminal, the users.json does not get reset)

Here is the full log:

```
PS C:\Users\X\OneDrive\Desktop\reddit-placebot-2023-master> ./redditplacebot -minX=# -minY=#
Waiting for login to finish...
2023-07-25T01:21:52.979+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
2023-07-25T01:21:57.461+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
Login finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x50a3cf]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xa218090)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/board.go:43 +0x7f
main.(*Worker).Run(0xa206260)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/worker.go:37 +0x4e
main.main()
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:47 +0x5b8
```

**Comment by Edouard127** [comment]
It crashes because it couldn't login into any accounts

**Comment by Obelisx** [comment]
> It crashes because it couldn't login into any accounts

Instead of PowerShell, I now ran it in terminal, and it indeed said:

```
C:\Users\X>C:\Users\X\OneDrive\Desktop\reddit-placebot-2023-master\redditplacebot.exe -minX=# -minY=#
panic: Please add users to the users.json file

goroutine 1 [running]:
main.readClients(0xa142380, 0xa128b40)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:55 +0xd00
main.main()
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:26 +0x365
```

But it is strange, because the users.json really has 2 accounts in it. I just succesfully logged in with both of them on the website, so they're also not banned

**Comment by Edouard127** [comment]
You're supposed the rename the file to users.json

**Comment by Edouard127** [comment]
Cannot reproduce
